# Generated by Django 5.1 on 2024-08-24 15:12

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batchmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('phone_number', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branchmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batchmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_ticket', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('profile', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('address', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('parent_phone_number', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sectionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_lab', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branchmodel')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semestermodels')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facultymodel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sectionmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentmodel')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timetablemodel')),
            ],
        ),
        migrations.CreateModel(
            name='TimingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batchmodel')),
            ],
        ),
        migrations.AddField(
            model_name='timetablemodel',
            name='timing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timingmodel'),
        ),
        migrations.AddConstraint(
            model_name='branchmodel',
            constraint=models.UniqueConstraint(fields=('batch', 'name'), name='unique_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='sectionmodel',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_section_name'),
        ),
        migrations.AddConstraint(
            model_name='semestermodels',
            constraint=models.UniqueConstraint(fields=('batch', 'year', 'semester'), name='unique_batch_year_semester'),
        ),
        migrations.AddConstraint(
            model_name='subjectmodel',
            constraint=models.UniqueConstraint(fields=('name', 'semester'), name='unique_branch_name_semester'),
        ),
        migrations.AddConstraint(
            model_name='attendancemodel',
            constraint=models.UniqueConstraint(fields=('student', 'period'), name='unique_period_student'),
        ),
        migrations.AddConstraint(
            model_name='timingmodel',
            constraint=models.UniqueConstraint(fields=('name', 'batch'), name='unique_name_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='timingmodel',
            constraint=models.UniqueConstraint(fields=('start', 'end', 'batch'), name='unique_time_slot_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='timetablemodel',
            constraint=models.UniqueConstraint(fields=('timing', 'section', 'date', 'subject'), name='unique_timing_date_period'),
        ),
    ]
