# Generated by Django 5.1 on 2024-08-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymodel',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facultymodel',
            name='profile',
            field=models.ImageField(null=True, upload_to='profiles/faculty'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='profile',
            field=models.ImageField(upload_to='profiles/students'),
        ),
    ]
