# Generated by Django 5.0.6 on 2024-07-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semestermodels",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.batchmodel"
            ),
        ),
    ]
