# Generated by Django 5.1 on 2024-08-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_facultymodel_email_alter_facultymodel_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultymodel',
            name='email',
        ),
    ]
