# Generated by Django 5.0.6 on 2024-07-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_timingmodel_name_timingmodel_unique_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timingmodel",
            name="unique_name",
        ),
        migrations.AddField(
            model_name="subjectmodel",
            name="branch",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.branchmodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="timingmodel",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name="subjectmodel",
            constraint=models.UniqueConstraint(
                fields=("name", "semester", "branch"),
                name="unique_branch_name_semester",
            ),
        ),
    ]
