# Generated by Django 5.0.6 on 2024-07-05 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_timingmodel_unique_name_subjectmodel_branch_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="semestermodels",
            name="unique_batch_year_semester",
        ),
        migrations.RemoveConstraint(
            model_name="subjectmodel",
            name="unique_branch_name_semester",
        ),
        migrations.RemoveField(
            model_name="semestermodels",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="subjectmodel",
            name="branch",
        ),
        migrations.AddField(
            model_name="semestermodels",
            name="branch",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.branchmodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="timingmodel",
            unique_together={("start", "end")},
        ),
        migrations.AddConstraint(
            model_name="semestermodels",
            constraint=models.UniqueConstraint(
                fields=("branch", "year", "semester"), name="unique_batch_year_semester"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectmodel",
            constraint=models.UniqueConstraint(
                fields=("name", "semester"), name="unique_branch_name_semester"
            ),
        ),
    ]
