# Generated by Django 5.0.6 on 2024-07-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_semestermodels_unique_batch_year_semester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultymodel",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
