# Generated by Django 5.0.6 on 2024-07-16 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_facultymodel_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetablemodel",
            name="period",
        ),
        migrations.AddField(
            model_name="timetablemodel",
            name="faculty",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.facultymodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timetablemodel",
            name="subject",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.subjectmodel",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PeriodModel",
        ),
    ]
