# Generated by Django 5.0.6 on 2024-07-18 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_timetablemodel_period_timetablemodel_faculty_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="semestermodels",
            name="unique_batch_year_semester",
        ),
        migrations.RemoveField(
            model_name="semestermodels",
            name="branch",
        ),
        migrations.AddField(
            model_name="semestermodels",
            name="batch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.batchmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="semestermodels",
            constraint=models.UniqueConstraint(
                fields=("batch", "year", "semester"), name="unique_batch_year_semester"
            ),
        ),
    ]
