# Generated by Django 5.0.6 on 2024-07-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_semestermodels_unique_batch_year_semester"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subjectmodel",
            name="unique_branch_name_semester",
        ),
    ]
