# Generated by Django 5.0.6 on 2024-07-18 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_subjectmodel_unique_branch_name_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semestermodels",
            name="batch",
        ),
        migrations.AddField(
            model_name="semestermodels",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.branchmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="semestermodels",
            constraint=models.UniqueConstraint(
                fields=("branch", "year", "semester"), name="unique_batch_year_semester"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectmodel",
            constraint=models.UniqueConstraint(
                fields=("name", "semester"), name="unique_branch_name_semester"
            ),
        ),
    ]
