# Generated by Django 5.0.6 on 2024-07-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_semestermodels_unique_batch_year_semester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultymodel",
            name="department",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="facultymodel",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
