# Generated by Django 5.0.6 on 2024-07-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_attendancemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetablemodel",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
