# Generated by Django 5.0.6 on 2024-07-24 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_timetablemodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectmodel",
            name="branch",
            field=models.ForeignKey(
                default=13,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.branchmodel",
            ),
            preserve_default=False,
        ),
    ]
