# Generated by Django 5.0.6 on 2024-07-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_subjectmodel_branch"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="attendancemodel",
            constraint=models.UniqueConstraint(
                fields=("student", "period"), name="unique_period_student"
            ),
        ),
    ]
