# Generated by Django 5.0.6 on 2024-07-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_attendancemodel_unique_period_student"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="timetablemodel",
            constraint=models.UniqueConstraint(
                fields=("timing", "section", "date"),
                name="Already period exists in this time",
            ),
        ),
    ]
