# Generated by Django 5.0.6 on 2024-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_timetablemodel_already_period_exists_in_this_time"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timetablemodel",
            name="Already period exists in this time",
        ),
        migrations.AddConstraint(
            model_name="timetablemodel",
            constraint=models.UniqueConstraint(
                fields=("timing", "section", "date"),
                name="unique_timing_date_period",
                violation_error_message="Period already exists in this time",
            ),
        ),
    ]
