# Generated by Django 5.0.6 on 2024-07-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0020_remove_timetablemodel_already_period_exists_in_this_time_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timetablemodel",
            name="unique_timing_date_period",
        ),
        migrations.AlterUniqueTogether(
            name="batchmodel",
            unique_together={("start", "end")},
        ),
        migrations.AddConstraint(
            model_name="timetablemodel",
            constraint=models.UniqueConstraint(
                fields=("timing", "section", "date"), name="unique_timing_date_period"
            ),
        ),
    ]
