# Generated by Django 5.0.6 on 2024-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_timingmodel_unique_together_timingmodel_batch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timingmodel",
            name="name",
            field=models.CharField(max_length=10),
        ),
    ]
