# Generated by Django 5.0 on 2024-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_facultymodel_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subjectmodel',
            name='unique_branch_name_semester',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='subjectmodel',
            constraint=models.UniqueConstraint(fields=('name', 'is_lab', 'semester'), name='unique_branch_name_semester'),
        ),
    ]
