# Generated by Django 5.1 on 2024-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_remove_facultymodel_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="test")),
            ],
        ),
    ]
