# Generated by Django 5.1 on 2024-08-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_test_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="img",
            field=models.ImageField(upload_to="test"),
        ),
    ]
