# Generated by Django 5.1 on 2024-08-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_test_img"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
