# Generated by Django 5.1 on 2024-08-20 06:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_delete_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodel",
            name="profile",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
