# Generated by Django 5.1 on 2024-08-20 06:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_alter_studentmodel_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultymodel",
            name="profile",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
